[device]
id=cucqif9x85jz6tr4


[model]
name=uitars_1_5
url=http://10.221.105.108:42401/v1


[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3


[task]
task_file=data/longtail.csv
output=results/uitars1.5_1121_longtail
