[device]
id=cucqif9x85jz6tr4


[model]
# Your GPT-4o API URL
API_url = # Your GPT-4o API URL
# Your GPT-4o API Token
token= #Your GPT-4o API Token
# Choose between "api" and "local". api: use the qwen api. local: use the local qwen checkpoint
caption_call_method = "api"
# Choose between "qwen-vl-plus" and "qwen-vl-max" if use api method. Choose between "qwen-vl-chat" and "qwen-vl-chat-int4" if use local method.
caption_model = "qwen-vl-plus"
# If you choose the api caption call method, input your Qwen api here
qwen_api = # Qwen api

[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3

[task]
task_file=data/longtail.csv
output=results/mobileagentv2_1121_longtail
# 相当于results_dir