[device]
id=9945aam77ld6y9u4


[model]
name=uitars_1_5
url=http://10.221.105.108:45101/v1


[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3


[task]
task_file=data/top12.csv
output=results/round1
