[device]
id=sconhuha9lmfnjy9


[model]
name=qwen2_5vl
url=http://10.***.***.***:*****/v1


[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3


[task]
task_file=data/MobileBench-OL - top12.csv
output=results/qwen2_5vl_base
