[device]
id=sconhuha9lmfnjy9


[model]
name=mobileagentv2 
# Your GPT-4o API URL
url =
# Your GPT-4o API Token
token = 
# Choose between "api" and "local". api: use the qwen api. local: use the local qwen checkpoint
caption_call_method = api
# Choose between "qwen-vl-plus" and "qwen-vl-max" if use api method. Choose between "qwen-vl-chat" and "qwen-vl-chat-int4" if use local method.
caption_model = qwen-vl-plus
# If you choose the api caption call method, input your Qwen api here
qwen_api = 

[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3

[task]
task_file=data/test_1sample.csv
output=results/mobileagentv2_test
# 相当于results_dir