[device]
id=sconhuha9lmfnjy9


[model]
name=uitars_1_5
url=http://10.221.105.108:42401/v1


[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=true

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3


[task]
task_file=data/top12-reset.csv
output=results/uitars1.5_1204_reset_2
