[device]
id=cucqif9x85jz6tr4


[model]
name=t3a
url=azure


[azure]
azure_endpoint=https://ui-agent-exp.openai.azure.com/
api_key=#your_own_key
model=gpt-4o
api_version=2024-02-15-preview
max_retry=2
temperature=0.0
max_length=512


[retry]
retry_rounds=2
connect_retry=3
fail_retry=1

[reset]
reset=false

[operation]
max_steps=20
back_times=
sleep_seconds_per_act=3


[task]
task_file=data/longtail.csv
output=results/t3a_1121_longtail